/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ReportRouteImport } from './routes/report'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListHostelRouteImport } from './routes/list-hostel'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup.index'
import { Route as SignupStudentRouteImport } from './routes/signup.student'
import { Route as SignupLandlordRouteImport } from './routes/signup.landlord'
import { Route as HostelHostelIdRouteImport } from './routes/hostel.$hostelId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListHostelRoute = ListHostelRouteImport.update({
  id: '/list-hostel',
  path: '/list-hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupStudentRoute = SignupStudentRouteImport.update({
  id: '/signup/student',
  path: '/signup/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupLandlordRoute = SignupLandlordRouteImport.update({
  id: '/signup/landlord',
  path: '/signup/landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelHostelIdRoute = HostelHostelIdRouteImport.update({
  id: '/hostel/$hostelId',
  path: '/hostel/$hostelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/list-hostel': typeof ListHostelRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/wishlist': typeof WishlistRoute
  '/hostel/$hostelId': typeof HostelHostelIdRoute
  '/signup/landlord': typeof SignupLandlordRoute
  '/signup/student': typeof SignupStudentRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/list-hostel': typeof ListHostelRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/wishlist': typeof WishlistRoute
  '/hostel/$hostelId': typeof HostelHostelIdRoute
  '/signup/landlord': typeof SignupLandlordRoute
  '/signup/student': typeof SignupStudentRoute
  '/signup': typeof SignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/list-hostel': typeof ListHostelRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/wishlist': typeof WishlistRoute
  '/hostel/$hostelId': typeof HostelHostelIdRoute
  '/signup/landlord': typeof SignupLandlordRoute
  '/signup/student': typeof SignupStudentRoute
  '/signup/': typeof SignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/help'
    | '/list-hostel'
    | '/login'
    | '/report'
    | '/wishlist'
    | '/hostel/$hostelId'
    | '/signup/landlord'
    | '/signup/student'
    | '/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/help'
    | '/list-hostel'
    | '/login'
    | '/report'
    | '/wishlist'
    | '/hostel/$hostelId'
    | '/signup/landlord'
    | '/signup/student'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/help'
    | '/list-hostel'
    | '/login'
    | '/report'
    | '/wishlist'
    | '/hostel/$hostelId'
    | '/signup/landlord'
    | '/signup/student'
    | '/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  ListHostelRoute: typeof ListHostelRoute
  LoginRoute: typeof LoginRoute
  ReportRoute: typeof ReportRoute
  WishlistRoute: typeof WishlistRoute
  HostelHostelIdRoute: typeof HostelHostelIdRoute
  SignupLandlordRoute: typeof SignupLandlordRoute
  SignupStudentRoute: typeof SignupStudentRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-hostel': {
      id: '/list-hostel'
      path: '/list-hostel'
      fullPath: '/list-hostel'
      preLoaderRoute: typeof ListHostelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/student': {
      id: '/signup/student'
      path: '/signup/student'
      fullPath: '/signup/student'
      preLoaderRoute: typeof SignupStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/landlord': {
      id: '/signup/landlord'
      path: '/signup/landlord'
      fullPath: '/signup/landlord'
      preLoaderRoute: typeof SignupLandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel/$hostelId': {
      id: '/hostel/$hostelId'
      path: '/hostel/$hostelId'
      fullPath: '/hostel/$hostelId'
      preLoaderRoute: typeof HostelHostelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  ListHostelRoute: ListHostelRoute,
  LoginRoute: LoginRoute,
  ReportRoute: ReportRoute,
  WishlistRoute: WishlistRoute,
  HostelHostelIdRoute: HostelHostelIdRoute,
  SignupLandlordRoute: SignupLandlordRoute,
  SignupStudentRoute: SignupStudentRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
